version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: messages_router
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mqseries:
    image: ibmcom/mq:latest
    container_name: ibm-mq
    restart: always
    environment:
      LICENSE: accept
      MQ_QMGR_NAME: QM1
      MQ_ADMIN_PASSWORD: passw0rd
    ports:
      - "1414:1414"  # Port MQ
      - "9443:9443"  # Interface web IBM MQ

volumes:
  postgres_data:
